development:
  adapter: postgresql
  encoding: unicode
  database: poppage_development
  pool: 5
  username: chendriksen
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: poppage_test
  pool: 5
  username: chendriksen
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: poppage_production
  pool: 5
  username: chendriksen
  password: 
